packages:
  - apps/*
  - packages/*

overrides:
  axios: 1.18.1
  brace-expansion@<=5.0.7: ^5.0.8
  ws: 8.21.1

allowBuilds:
  '@parcel/watcher': true
  '@reown/appkit': true
  bufferutil: false
  esbuild: true
  keccak: true
  utf-8-validate: false

minimumReleaseAgeExclude:
  - sass@1.101.7
  - brace-expansion@5.0.8

patchedDependencies:
  minimatch@3.1.5: patches/minimatch@3.1.5.patch
