packages:
  - apps/*
  - packages/*

overrides:
  axios: 1.18.1
  ws: 8.21.1

allowBuilds:
  '@parcel/watcher': true
  '@reown/appkit': true
  bufferutil: false
  esbuild: true
  keccak: true
  utf-8-validate: false

minimumReleaseAgeExclude:
  - sass@1.101.7
